### ISSUE TITLE
Depends on local_aws that has not been updated recently

### ISSUE THREAD

**Issue by mudrd8mz** [catalyst/moodle-tool_s3logs#4]
This plugin declares dependency on another `local_aws` plugin. The latest available version of local_aws in the [plugins directory](https://moodle.org/plugins/local_aws) is marked as supporting Moodle versions up to 3.3 only.

This may confuse some admins. Please consider updating the list of supported Moodle versions for the local_aws plugin. Thanks.

**Comment by dmitriim** [comment]
@mudrd8mz  thanks for pointing out. I have updated versions list for  local_aws https://moodle.org/plugins/pluginversions.php?plugin=local_aws
