### ISSUE TITLE
tool_s3logs\client is not a valid namespace

### ISSUE THREAD

**Issue by mudrd8mz** [catalyst/moodle-tool_s3logs#5]
Moodle has certain rules on how namespaces are selected. As per https://docs.moodle.org/dev/Coding_style#Rules_for_level2 your current namespace `tool_s3logs\client` should be `tool_s3logs\local\client`.

**Comment by dmitriim** [comment]
Hi @mudrd8mz !

I have checked a couple of open source plugins that have in our git repo and they all do not follow this recommendation/rule. Is it something new? Do I understand correctly if you want to organise your files in folders, then you need to have classes/local/folder1  classes/local/folder2 and not classes/lfolder1  As long as folderN is not part of the core? I find this a bit confusing. 

Also would be probably good to add this case as an example/reference to https://docs.moodle.org/dev/Automatic_class_loading#Namespaces

**Comment by dmitriim** [comment]
fixed anyway

**Comment by mudrd8mz** [comment]
As far as I can see, the https://docs.moodle.org/dev/Automatic_class_loading#Namespaces has a note about it:

> Note there are restrictions on valid choices for the first and second level namespaces in Moodle - see Coding_style#Namespaces for more info

**Comment by brendanheywood** [comment]
That is something I have very rarely seen done right (including my code). This should be something that fails CI loudly, I've opened that here:

https://github.com/blackboard-open-source/moodle-plugin-ci/issues/97

**Comment by dmitriim** [comment]
Yeah. I've been doing plugin dev for ages and somehow this slipped out from me. I'll be pointing to this during my code reviews. @mudrd8mz  thanks for heads up
