### ISSUE TITLE
Privacy null_provider does not seem appropriate

### ISSUE THREAD

**Issue by mudrd8mz** [catalyst/moodle-tool_s3logs#6]
I am not sure it is appropriate to declare the plugin as not processing personal data. It exports the contents of the `logstore_standard_log` table into an external system. Administrators having this installed, must be informed about this, so that they can prepare relevant site & privacy policies for their site, for the users to agree with it.

Please refer to https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

**Comment by dmitriim** [comment]
Privacy provider updated.

**Comment by danmarsden** [comment]
@dmitriim - doesn't look like this landed in the master branch? - or am I missing something?

**Comment by dmitriim** [comment]
Hmm... not sure what was happening... Picking it up again...

**Comment by dmitriim** [comment]
@danmarsden  are you able to review? https://github.com/catalyst/moodle-tool_s3logs/pull/16

**Comment by dmitriim** [comment]
Never mind. Was merged in.
